FROM samvantran/spark-dcos-gpu:minpatch-nv390-cuda9-cudnn7115-tf15

ARG AWS_JAVA_SDK_JAR_SHA1="650f07e69b071cbf41c32d4ea35fd6bbba8e6793"
ARG AWS_JAVA_SDK_URL="https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk"
ARG AWS_JAVA_SDK_VERSION="1.7.5"
ARG HADOOP_AWS_JAR_SHA1="d997f4cf765ca360b69c8bbcaab8785e7c37a55d"
ARG HADOOP_AWS_URL="https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws"
ARG HADOOP_AWS_VERSION="2.7.6"
ARG HADOOP_HDFS_HOME="/opt/hadoop"
ARG HADOOP_MAJOR_VERSION="2.7"
ARG HADOOP_SHA256="f2327ea93f4bc5a5d7150dee8e0ede196d3a77ff8526a7dd05a48a09aae25669"
ARG HADOOP_URL="http://www-us.apache.org/dist/hadoop/common"
ARG HADOOP_VERSION="2.7.6"

RUN rm -rf /opt/spark/* \
    && echo /opt/spark \
    && cd /tmp \
    && curl --retry 3 -fsSL -O "https://infinity-artifacts.s3.amazonaws.com/spark/spark-2.2.1-bin-2.7.3.tgz" \
    && echo "Downloaded https://infinity-artifacts.s3.amazonaws.com/spark/spark-2.2.1-bin-2.7.3.tgz" \
    && tar xf "spark-2.2.1-bin-2.7.3.tgz" -C "${SPARK_HOME}" --strip-components=1 \
    && cd "${SPARK_HOME}/jars" \
    && curl --retry 3 -fsSL -O "${AWS_JAVA_SDK_URL}/${AWS_JAVA_SDK_VERSION}/aws-java-sdk-${AWS_JAVA_SDK_VERSION}.jar" \
    && echo "${AWS_JAVA_SDK_JAR_SHA1} aws-java-sdk-${AWS_JAVA_SDK_VERSION}.jar" | sha1sum -c - \
    && curl --retry 3 -fsSL -O "${HADOOP_AWS_URL}/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar" \
    && echo "${HADOOP_AWS_JAR_SHA1} hadoop-aws-${HADOOP_AWS_VERSION}.jar" | sha1sum -c - \
    && rm -rf /tmp/*

COPY conf/ "${SPARK_HOME}/conf/" 

RUN chmod -R ugo+rw "${SPARK_HOME}/conf"

# Add external jar for pushing metrics via StatsD (https://github.com/vidhyaarvind/spark-statsd)
COPY jars/spark-statsd-1.0.0.jar $SPARK_HOME/jars/spark-statsd-1.0.0.jar

WORKDIR "${SPARK_HOME}"
